import type {NextPage,GetStaticProps} from "next";
import { Namespace } from 'react-i18next';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import nextI18NextConfig from '@/../next-i18next.config.js';
import Head from "next/head";
import {Button} from "../src/components/atom/Button/Button";

const i18nextNameSpaces: Namespace[] = ['navbar','seo', 'common', 'login', 'about'];

export const getStaticProps: GetStaticProps = async ({ locale }) => {
    // 必要なリソースをロードし、propsとして受け渡す
    const translation = await serverSideTranslations(locale!, i18nextNameSpaces as string[], nextI18NextConfig);
    return { props: { ...translation} };
};

const Home: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            {/* eslint-disable-next-line react/jsx-no-undef */}
            <main className="py-10 px-5 flex flex-col gap-10">
                <section>
                    <div className="flex flex-row flex-wrap gap-10">
                        <Button btnType="primary">Primary</Button>
                        <Button btnType="secondary">Secondary</Button>
                        <Button btnType="accent">Accent</Button>
                        <Button btnType="ghost">Ghost</Button>
                        <Button btnType="link">Link</Button>
                        <Button btnType="success">Success</Button>
                        <Button btnType="error">Error</Button>
                    </div>
                </section>
            </main>
        </div>
    );
};

export default Home;